---
title: "Task 2"
subtitle: "Survey Data" 
author: "Laurie Kell & Alex Tidd"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r knitr, echo=FALSE}
library(knitr)

opts_chunk$set(comment=NA, fig.width =8, 
               fig.height=6,
               fig.path  ="../tex/",
               warning=FALSE, 
               message=FALSE, 
               error  =FALSE, 
               echo   =FALSE,
               cache  =TRUE)
iFig=0
iTab=0
```
```{r pkgs}
library(DBI) 
library(RPostgreSQL) 
library(dplyr) 
library(plyr) 
library(reshape) 
library(maptools) 
library(ggplot2) 

options(scipen = 999) 
```
```{r dir}
dirMy=dirname(FLife:::getScriptPath())
#dirMy="/home/laurence/Desktop/sea++/mydas/tasks/task2"
dirInp=file.path(dirMy,"inputs")
dirDat=file.path(dirMy,"data")
```
```{r postgres, eval=FALSE}
drv=dbDriver("PostgreSQL") 

con=dbConnect(drv, host    ='postgresql-seascope.csffkpr9jjjn.eu-west-2.rds.amazonaws.com', 
                   dbname  ='mydasDev', 
                   port    =5432, 
                   user    ='MydasApplication', 
                   password='gmit2017!') 

survey=dbGetQuery(con,"SELECT * FROM data_surveybio") 
stecf =dbGetQuery(con,"SELECT * FROM data_stecflandings")

save(survey,file=file.path(dirDat,"survey.RData"),compress="xz")
save(stecf, file=file.path(dirDat,"stecf.RData"),compress="xz")
```

```{r plot}
library(reldist)
load(file.path("/home/laurence/Desktop/sea++/mydas/tasks/task1/data","survey.RData"))
load(file.path("/home/laurence/Desktop/sea++/mydas/tasks/task1/data","lh.RData"))

weighted.var.se<-function(x, w, na.rm=FALSE){
  #  Computes the variance of a weighted mean following Cochran 1977 definition
  if (na.rm) { w <- w[i <- !is.na(x)]; x <- x[i] }
  n = length(w)
  xWbar = weighted.mean(x,w,na.rm=na.rm)
  wbar = mean(w)
  out = n/((n-1)*sum(w)^2)*(sum((w*x-wbar*xWbar)^2)
                -2*xWbar*sum((w-wbar)*(w*x-wbar*xWbar))+xWbar^2*sum((w-wbar)^2))
  
  return(out)}

ln=ddply(survey[,c("speciesgp","year","ices_division","fishlength_cm","number")],
         .(speciesgp,year), with,
      data.frame(ln =sum(fishlength_cm*number)/sum(number),
                 se =weighted.var.se(fishlength_cm,number),
                 p25=wtd.quantile(fishlength_cm,weight=number,q=0.25),
                 p75=wtd.quantile(fishlength_cm,weight=number,q=0.75)))

rln=ldply(lh,function(x) data.frame(linf=mean(x["linf"],na.rm=T),l50=mean(x["lmat"],na.rm=T)))
names(rln)[1]="speciesgp"

ggplot(ln)+
  geom_line(aes(year,ln),position=position_dodge(width = 1))+
  geom_point(aes(year,ln),position=position_dodge(width = 1))+
  geom_linerange(aes(year,ymin=qnorm(0.025,ln,se), 
                           ymax=qnorm(0.975,ln,se)),position=position_dodge(width = 1))+
  geom_hline(aes(yintercept=linf),data=rln)+
  geom_hline(aes(yintercept=l50),data=rln)+
  facet_wrap(~speciesgp,scales="free_y")+
  theme_bw()+xlab("Year")+ylab("Length (cm)")
```
**Figure `r iFig=iFig+1; iFig`.** Mean length with 95% CIs, $L_{\infty}$ and $L_{mat}$ are also shown.

```{r plot-iles}
ln=ddply(survey[,c("speciesgp","year","fishlength_cm","number")],
         .(speciesgp,year), with,
      data.frame(ln =sum(fishlength_cm*number)/sum(number),
                 se =weighted.var.se(fishlength_cm,number),
                 p25=wtd.quantile(fishlength_cm,weight=number,q=0.25),
                 p75=wtd.quantile(fishlength_cm,weight=number,q=0.75)))

ggplot(ln)+
  geom_line(aes(year,ln))+
  geom_line(aes(year,p25),col="grey50")+
  geom_line(aes(year,p75),col="grey50")+
  geom_hline(aes(yintercept=linf),data=rln)+
  geom_hline(aes(yintercept=l50),data=rln)+
  facet_wrap(~speciesgp,scales="free_y")+
  theme_bw()+xlab("Year")+ylab("Length (cm)")
```
**Figure `r iFig=iFig+1; iFig`.** Mean lenth with inter-quartile range, $L_{\infty}$ and $L_{mat}$ are also shown.

```{r plot2,fig.height=8}
dat=ddply(survey,.(speciesgp,ices_division,year),with,mean(densbiom_kg_sqkm))
dat=ddply(dat,.(speciesgp,ices_division),transform,cpue=V1/mean(V1))

ggplot(dat) +
  geom_line( aes(year,cpue,col=ices_division))+
  geom_point(aes(year,cpue,col=ices_division),size=.5)+
  facet_wrap(~speciesgp,scale="free_y",ncol=3)+
  theme_bw()+
  theme(legend.position="bottom")
```
**Figure `r iFig=iFig+1; iFig`.** Time series of surveys. 


```{r plot4,fig.height=10}
load(file.path("/home/laurence/Desktop/sea++/mydas/data","stecf.RData"))

dat=ddply(stecf,.(species,division,year),with,sum(landings))

ggplot(dat) +
  geom_line( aes(year,V1,col=division))+
  geom_point(aes(year,V1,col=division),size=.5)+
  facet_wrap(~species,scale="free_y",ncol=3)+
  theme_bw()+
  theme(legend.position="bottom")
```
**Figure `r iFig=iFig+1; iFig`.** Time series of catches. 
