---
title: "MyDas"
subtitle: "Stock Assssments"
author: "Laurie Kell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown:::pdf_document
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
tags: FLPKG FLR
license: Creative Commons Attribution-ShareAlike 4.0 International
---

https://github.com/ices-tools-prod/icesSAG

```{r knitr, echo=FALSE}
library(knitr)

opts_chunk$set(comment=NA, 
               fig.width =8, 
               fig.height=6,
               fig.path  ="../tex/sa",
               warning   =FALSE, 
               message   =FALSE, 
               error     =FALSE, 
               echo      =FALSE,
               cache     =TRUE,
               cache.path="../cache/sa")
iFig=0
iTab=0
```
```{r pkgs}
library(FLCore)
library(ggplotFL)
library(FLife)
library(plyr)
library(dplyr)
library(FLife)
library(stringr)

theme_set(theme_bw())
```
```{r dir}
dirMy=dirname(FLife:::getScriptPath())
#dirMy="/home/laurence/Desktop/sea++/mydas/tasks/task2"

dirInp="/home/laurence/Desktop/rfmo/ices/"
dirDat="/home/laurence/Desktop/sea++/mydas/tasks/task2/data"
```

# Stocks and species
```{r stocks}
cs=read.csv(file.path(dirInp,"cs/2017/StockAssessmentGraphs_2017128ijaewuckpic5ftyotcrcu20f.csv"))
ns=read.csv(file.path(dirInp,"ns/2017/StockAssessmentGraphs_2017128ijaewuckpic5ftyotcrcu20f.csv"))

stocks=rbind(data.frame(wg="Celtic Sea",stock=unique(cs[,"FishStock"])),
             data.frame(wg="North Sea", stock=unique(ns[,"FishStock"])))

stocks=mutate(stocks,code  =substr(stock,1,regexec('\\.',ac(stock))[[1]][1]-1),
                     x1    =substr(stock,  regexec('\\.',ac(stock))[[1]][1]+1,nchar(ac(stock))),
                     region=substr(x1,   1,regexec('\\.',x1)[[1]][1]-1),
                     area  =substr(x1,     regexec('\\.',x1)[[1]][1]+1,nchar(x1)))[,-4]

spp=read.csv(file.path(dirInp,"species.txt"),header=FALSE)[,-2]
spp=transmute(spp,code=str_trim(tolower(V1)),spp=str_trim(tolower(V3)),worm=V4)

stocks=merge(stocks,spp,by="code",all.x=TRUE)
stocks=stocks[do.call("order",stocks[,c("code","wg","area")]),]

substr(stocks$spp,1,1)=toupper(substr(stocks$spp,1,1))

stocks[,c("code","spp","wg","area")]
```

Missing species
```{r lhparams}
unique(subset(stocks,is.na(spp))$code)
```

#Stock Assessments 
```{r, assessment}
nms=c("Cod North Sea", "Haddock North Sea","Whiting North Sea","Saithe North Sea", 
      "Plaice North Sea", "Sole North Sea",
      "Cod Celtic Sea","Haddock Celtic Sea","Whiting Celtic Sea")
spp=c("Gadus morhua","Melanogrammus aeglefinus","Merlangius merlangus","Pollachius virens",
      "Pleuronectes platessa","Solea solea")
spp=spp[c(1:6,1:3)]
sea=c(rep("North Sea",6),rep("Celtic Sea",3))
stock=c("cod347","hadns","whg3747d","ple27420","solnsea","sains",
        "cod7ek","whg7bk","hadcs")
nms=data.frame(nms,spp,sea,stock)

load("/home/laurence/Desktop/sea++/stecf/data/stk.RData")
stk=stk["hadns"]

load("/home/laurence/Desktop/rfmo/ices/ns/2017/cod347/cod347_FLStockObject_wgnssk17_nscod17_ass06.RData")
stk["codns"]=cod

load("/home/laurence/Desktop/rfmo/ices/ns/2017/whg3747d/whg.27.47d.stock.Rdata")
stk["whgns"]=x.stock

load("/home/laurence/Desktop/rfmo/ices/ns/2017/ple27420/ple.27.420_stock.object.Rdata")
stk["plens"]=ass.stockOrigDisc

load("/home/laurence/Desktop/rfmo/ices/ns/2017/solnsea/sol-nsea_ass.stock_workspace.Rdata")
stk["solns"]=ass.stock

load("/home/laurence/Desktop/rfmo/ices/ns/2017/ple27420/ple.27.420_stock.object.Rdata")
stk["sains"]=ass.stock

load("/home/laurence/Desktop/rfmo/ices/cs/2017/cod7ek/xsa.stock.Rdata")
stk["codcs"]=xsa.stock

load("/home/laurence/Desktop/rfmo/ices/cs/2017/whg7bk/xsa.Rdata")
stk["whgcs"]=stock

load("/home/laurence/Desktop/rfmo/ices/cs/2017/colm/HAD_stock.RData")
stk["hadcs"]=stock

stk=llply(stk[c("codns","hadns","sains","whgns","plens","solns","codcs","hadcs","whgcs")],
                   function(x) iter(x,1))

save(nms,file=file.path(dirDat,"nms.RData"),compress="xz")
save(stk,file=file.path(dirDat,"stk.RData"),compress="xz")
```

```{r, stk-ts}
load(file.path(dirDat,"stk.RData"))

stkTs=ldply(stk,
          function(x) 
              model.frame(FLQuants(
                ssb    =ssb( x),
                f      =fbar(x),
                catch  =catch(x),
                cpue   =catch(x)%/%fbar(x),
                recruit=rec(x),
                stock  =stock(x),
                hrate  =catch(x)%/%stock(x),
                pgwt   =stock.n(x)[ac(range(x)["plusgroup"])]%*%stock.wt(x)[ac(range(x)["plusgroup"])],
                pgn    =stock.n(x)[ac(range(x)["plusgroup"])],
                cmnwt  =FLQuant(aaply(catch.n(x)%*%catch.wt(x),2:6,sum))%/%
                            FLQuant(aaply(catch.n(x),2:6,sum)),
                smnwt  =FLQuant(aaply(stock.n(x)%*%stock.wt(x),2:6,sum))%/%
                            FLQuant(aaply(stock.n(x),2:6,sum)),
                cmnage =FLQuant(aaply(catch.n(x)%*%ages(catch.wt(x)),2:6,sum))%/%
                            FLQuant(aaply(catch.n(x),2:6,sum)),
                smnage =FLQuant(aaply(stock.n(x)%*%ages(stock.wt(x)),2:6,sum))%/%
                            FLQuant(aaply(stock.n(x),2:6,sum))
                ),drop=TRUE))
save(stkTs,file=file.path(dirDat,"stkTs.RData"))
```

```{r, ssb}
ggplot(stkTs)+
  geom_line(aes(year,ssb,col=.id))+
  guides(colour=guide_legend(title="Stock",title.position="left"))+
  xlab("Year")+ylab("SSB")+
  theme_bw()+
  theme(legend.position="bottom")
```
**Figure `r iFig=iFig+1; paste("A1.",iFig,sep="")`**

```{r, harvest}
ggplot(stkTs)+
  geom_line(aes(year,f,col=.id))+
  guides(colour=guide_legend(title="Stock",title.position="left"))+
  xlab("Year")+ylab("F")+
  theme_bw()+
  theme(legend.position="bottom")
```
**Figure `r iFig=iFig+1; paste("A1.",iFig,sep="")`**

```{r, yield}
ggplot(stkTs)+
  geom_line(aes(year, catch,col=.id))+
  guides(colour=guide_legend(title="Stock",title.position="left"))+
  xlab("Year")+ylab("Catch")+
  theme_bw()+
  theme(legend.position="bottom")
```
**Figure `r iFig=iFig+1; paste("A1.",iFig,sep="")`**

```{r, ce}
ggplot(stkTs)+
  geom_line(aes(year,cpue,col=.id))+
  guides(colour=guide_legend(title="Stock",title.position="left"))+
  xlab("Year")+ylab("CPUE")+
  theme_bw()+
  theme(legend.position="bottom")
```
**Figure `r iFig=iFig+1; paste("A1.",iFig,sep="")`**

```{r, rec}
ggplot(stkTs)+
  geom_line(aes(year,recruit,col=.id))+
  guides(colour=guide_legend(title="Stock",title.position="left"))+
  xlab("Year")+ylab("Recruitment")+
  theme_bw()+
  theme(legend.position="bottom")
```
**Figure `r iFig=iFig+1; paste("A1.",iFig,sep="")`**

```{r, biomass}
ggplot(stkTs)+
  geom_line(aes(year,stock,col=.id))+
  guides(colour=guide_legend(title="Stock",title.position="left"))+
  xlab("Year")+ylab("Biomass")+
  theme_bw()+
  theme(legend.position="bottom")
```
**Figure `r iFig=iFig+1; paste("A1.",iFig,sep="")`**

```{r, hrate}
ggplot(stkTs)+
  geom_line(aes(year,hrate,col=.id))+
  guides(colour=guide_legend(title="Stock",title.position="left"))+
  xlab("Year")+ylab("Harvest Rate")+
  theme_bw()+
  theme(legend.position="bottom")
```
**Figure `r iFig=iFig+1; paste("A1.",iFig,sep="")`**

##Indices
```{r, index-wg}
load("/home/laurence/Desktop/rfmo/ices/ns/2017/ple27420/ple.27.420_stock.object.Rdata")
idx=list("solns"=indices)

load("/home/laurence/Desktop/rfmo/ices/cs/2017/cod7ek/cod_idx.RData")
idx["codcs"]=idx

load("/home/laurence/Desktop/rfmo/ices/cs/2017/colm/HAD_tunning.RData")
idx["hadcs"]=tun

load("/home/laurence/Desktop/rfmo/ices/cs/2017/colm/PLE_tun.Rdata")
idx["plecs"]=tun

load("/home/laurence/Desktop/rfmo/ices/cs/2017/sol7fg/INPUT/sol7fg_stock.Rdata")
idx["solcs"]=tun
```

```{r, index-sa.org}
idxNs=list(mlply(c(
              "nscod_ass06_fc17",
	            "NS_saithe_corr_DATRASQ3_cw4sw_update",
	            "sam-tmb-01",
	            "sam-tmb-turbot-2017-01",
	            "sole20-24",
	            "sole2024_2018",
	            "sole2024_admb",
	            "sole3a2017",
	            "witch_2018_007",
	            "witch_2018_008"), function(x){ print(x)
	     readFLIndices(file.path("/home/laurence/Desktop/rfmo/ices","ns/2017/sa.org",x,"data/survey.dat"))}))
```

```{r}
idxCs=list(mlply(c(  
          "CODGis"
          #"HADPia",
          #"meg_rock_2016"
          ), function(x){ print(x)
	     readFLIndices(file.path("/home/laurence/Desktop/rfmo/ices","cs/2017/sa.org",x,"data/survey.dat"))}))

save(idx,idxNs,idxCs,file=file.path(dirDat,"idx.RData"),compress="xz")
```

```{r}
idxs=ldply(idxNs, function(x) 
          ldply(x, function(y) 
            ldply(y, function(z) as.data.frame(index(z),drop=TRUE))))
```

```{r spict}
bioNs=list(mdply(c("nsea-dab"), 
            function(x){ print(x)
read.csv(file.path("/home/laurence/Desktop/rfmo/ices","ns/2017/sa.org",x,"data/data.txt"),skip=1)}))

spictCs=c("meg_rock_2016",
          "Megrim_78_ADGWW2_IBP_update_Land",
          "Megrim_78_Cat_Porc_EVHO_Vigo1_2_IR1_ADGWW2",
          "Megrim_78_ADGWW2_IBP_update_Catch",
          "SPiCT-whg-iris",
          "nep_2021",
          "anb-78_ADGWW2",
          "anb_78",
          "anp_78PostADGWW2Correction",
          "ple-iris_ADGWW2")[-c(3:4,8)]
bioCs=mdply(spictCs, 
            function(x){ print(x)
  read.csv(file.path("/home/laurence/Desktop/rfmo/ices","cs/2017/sa.org",x,"data/data.txt"),skip=1)})
bioCs$stock=spictCs[bioCs$X1]
names(bioCs)=c("X1","year","yearEnd","fleet","obs","stock")
bioCs=bioCs[c(6,2:5)]

save(bioCs,bioNs,file="/home/laurence/Desktop/sea++/mydas/tasks/task2/data/bio.RData",compress="xz")
```

```{r}
ggplot(ddply(subset(bioCs,fleet!=1),.(stock,fleet),transform, 
             obs=diags:::stdz(log(obs))))+
  geom_point(aes(year,obs,col=ac(fleet)))+
  geom_line(aes(year,obs,col=ac(fleet)))+
  facet_wrap(~stock,scale="free_y")
```

```{r}
ggplot(ddply(subset(bioCs,fleet==1),.(stock,fleet),transform, 
             obs=diags:::stdz(log(obs))))+
  geom_point(aes(year,obs,col=ac(fleet)))+
  geom_line(aes(year,obs,col=ac(fleet)))+
  facet_wrap(~stock,scale="free_y")
```

