Elasticity: Figures
========================================================

```{r, echo=FALSE}
opts_chunk$set(comment=NA, fig.width =8, 
                           fig.height=6,
                           fig.path  ="../tex/par",
                           warning=FALSE, 
                           message=FALSE, 
                           error  =FALSE, 
                           echo   =FALSE,
                           cache  =FALSE)
```


```{r-par}
library(FLBRP)
library(plyr)

dirMy="/home/laurie/Ubuntu One/papers/Journal/elasticity"

#len cm
#Farley JH, Davis TL (1998) Reproductive dynamics of southern bluefin tuna, Thunnus maccoyii. Fishery Bulletin 96: 223–236.
fec=function(len) (4.78242*10e7)*len^7.530
lFn=function(wt,par) (wt/par["a"])^(1/par["b"])

load(paste(dirMy,"data/par.RData", sep="/"))
```

```{r-atage}
load(paste(dirMy,"data/par.RData",  sep="/"))
load(paste(dirMy,"data/atage.RData",sep="/"))

ggplot(ddply(atage,.(stock,Assumptions,qname),transform,data=data/max(data,na.rm=T)))+
  geom_point( aes(age,data,col=Assumptions),size=.75)+
  geom_smooth(aes(age,data,group=Assumptions,col=Assumptions))+
  facet_grid(qname~stock,scale="free")+
  xlab("Age")+ylab("")+theme_bw()
```

```{r}
fnM=function(par,len) exp(par["M1"]-par["M2"]*log(len))

hat=function(stock,Assumptions,par){
  ages=0:40
  ages=FLQuant(ages,dimnames=list(age=ages))
            
  #growth
  as.data.frame(FLQuants("Mass"             =len2wt(  par[,Assumptions,stock],vonB(par[,Assumptions,stock],ages)),
                         "Maturity"         =logistic(par[,Assumptions,stock],ages),
                         "Egg Production"   =logistic(par[,Assumptions,stock],ages)*len2wt(  par[,Assumptions,stock],vonB(par[,Assumptions,stock],ages)),
                         "Natural Mortality"=fnM(     par[,Assumptions,stock],vonB(par[,Assumptions,stock],ages))),drop=T)
              
            }

biol=mdply(expand.grid(stock=c("Herring","Cod","Bluefin"),Assumptions=c("WG","Life History"),stringsAsFactors=F),hat,par=par)        
```


**Mass**
```{r-mass,fig.width=6,fig.height=8}
ggplot(subset(atage,qname=="Mass"))+
  geom_point( aes(age,data,col=Assumptions),size=1)+
  geom_smooth(aes(age,data,group=Assumptions,col=Assumptions),span=.3)+
  facet_wrap(~stock,scale="free",ncol=1)+
  geom_line(aes(age,data,group=Assumptions,col=Assumptions), data=subset(biol,qname=="Mass"))+
  xlab("Age")+ylab("")+theme_bw()
```

**M**
```{r-m,fig.width=6,fig.height=8}
ggplot(subset(atage,qname=="Natural Mortality"))+
  geom_point( aes(age,data,col=Assumptions),size=1)+
  geom_smooth(aes(age,data,group=Assumptions,col=Assumptions),span=.3)+
  facet_wrap(~stock,scale="free",ncol=1)+
  geom_line(aes(age,data,group=Assumptions,col=Assumptions), data=subset(biol,qname=="Natural Mortality"))+
  xlab("Age")+ylab("")+theme_bw()
```

**Maturity**
```{r-mat,fig.width=6,fig.height=8}
ggplot(subset(atage,qname=="Maturity" & Assumptions=="wg"))+
  geom_point( aes(age,data,col=Assumptions),size=1)+
  geom_smooth(aes(age,data,group=Assumptions,col=Assumptions),span=.3)+
  facet_wrap(~stock,scale="free",ncol=1)+
  geom_line(aes(age,data,group=Assumptions,col=Assumptions), data=subset(biol,qname=="Maturity"))+
  xlab("Age")+ylab("")+theme_bw()
```

**Fecundity**
```{r-fec,fig.width=6,fig.height=8}
ggplot(subset(atage,qname=="Egg Production" & Assumptions=="wg"))+
  geom_point( aes(age,data,col=Assumptions),size=1)+
  geom_smooth(aes(age,data,group=Assumptions,col=Assumptions),span=.3)+
  facet_wrap(~stock,scale="free",ncol=1)+
  geom_line(aes(age,data,group=Assumptions,col=Assumptions), data=subset(biol,qname=="Egg Production"))+
  xlab("Age")+ylab("")+theme_bw()
```

```{r}
br=FLBRPs(alply(par, 2:4, function(x) lh(FLPar(x))))
```

```{r}
sim=function(x,b0=0.9,b1=.25,incr=.05,maxYr=90,rYr=5,tar=0.7){
  
  rf=refpts(x)
  
  dms=dimnames(rf)
  
  dms$refpt=c("initial",dms$refpt)
  rf=FLPar(NA,dimnames=dms)
  rf["initial","ssb"]=refpts(x)["virgin","ssb"]*b0
  
  refpts(x)=rf
  
  x=brp(x)
  
  fbar(x)=FLQuant(c(refpts(x)["initial","harvest"]),dimnames=list(year=1:90))
  fbar(x)[,10:90]=fbar(x)[,10:90]*cumprod(rep(1+incr,81))
  x=brp(x)
  
  rebuild=min(as.numeric(dimnames(ssb(x))$year[ssb(x)<(b1*c(refpts(x)["msy","ssb"]))])):maxYr
  
  fbar(x)[,rebuild]=c(refpts(x)["msy","harvest"])*tar
  
  fbar(x)[,(rebuild[]-1)[seq(rYr+1)]]=seq(c(fbar(x)[,rebuild[1]-1]),c(fbar(x)[,rebuild[1]]),length.out=rYr+1)
  
  fwd(x)}
```

```{r}
x=br[[6]]
stk=sim(x,incr=.1,b0=.75)

plot(stk)
```

```{r}
kobePhase(model.frame(FLQuants(stock=ssb(stk)%/%refpts(x)["msy","ssb"],harvest=fbar(stk)%/%refpts(x)["msy","harvest"]),drop=TRUE))+
  geom_path(aes(stock,harvest))
```




