wh---
title: "MyDas Data Collation"
subtitle: "Fishery Data" 
author: "Laurie Kell & Alex Tidd"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r dir}
dirMy =getwd()
dirInp=file.path(dirMy,"inputs")
dirDat=file.path(dirMy,"data")
```

```{r knitr, echo=FALSE}
library(knitr)

opts_chunk$set(comment=NA, fig.width =8, 
               fig.height=6,
               fig.path  ="../tex/",
               warning=FALSE, 
               message=FALSE, 
               error  =FALSE, 
               echo   =FALSE,
               cache  =TRUE)
iFig=0
iTab=0
```

```{r init}
library(DBI)
library(RPostgreSQL)
library(dplyr)
library(plyr)
library(reshape)
library(ggplot2)
library(maptools)

options(scipen = 999)
theme_set(theme_bw())
```


```{r postgres}
drv=dbDriver("PostgreSQL")

con  = dbConnect(drv, host = 'postgresql-seascope.csffkpr9jjjn.eu-west-2.rds.amazonaws.com',
                 dbname='mydasDev',
                 port = 5432,
                 user = 'MydasApplication',
                 password = 'gmit2017!')

stecf=dbGetQuery(con,"SELECT * FROM data_stecflandings")

stecf=transform(stecf,
                code     =tolower(speciesgp),
                stockarea=substr(stock,regexec('\\.',stock)[[1]][1]+1,nchar(stock)))
```

```{r summary-country}
dat=ddply(stecf,.(year,country,code),with, sum(landings))
ggplot(dat)+
  geom_line(aes(year,V1,col=country))+
  geom_line(aes(year,V1),col="black",data=subset(dat,country=="IRL"))+
  facet_wrap(~code,scales="free_y")+
  xlab("Year")+ylab("Landings")
```

**Figure `r iFig=iFig+1; iFig`.** Time series by species and country.

```{r summary-irl}
dat=ddply(subset(stecf,country="IRL"),.(year,gear,code),with, sum(landings))
ggplot(dat)+
  geom_line(aes(year,V1,col=gear))+
  facet_wrap(~code,scales="free_y")+
  xlab("Year")+ylab("Landings")
```

**Figure `r iFig=iFig+1; iFig`.** Time series of Irish catches by species and gear. 

\newpage

**Table `r iTab=iTab+1; iTab`.** Landings by species and area. 
```{r summary-area}
print(daply(stecf,.(area,code),with,as.integer(sum(landings,na.rm=TRUE))),digits=1)
```

```{r, eval=FALSE}
land2016         =subset(stecf, year %in% c(2016))

#remove area 4bc etc
land2016$flag    =ifelse(land2016$species %in% "LIN" & land2016$latitude <57.5 & land2016$area %in% "4", 1, 0)
land2016         =subset(land2016, flag==0)
land2016         =subset(land2016, !(area %in% "6B RFMO"))
area             =dbGetQuery(con,"SELECT * FROM div_area")
```

```{r, eval=FALSE}
drv  = dbDriver("PostgreSQL")

con  = dbConnect(drv, host = 'postgresql-seascope.csffkpr9jjjn.eu-west-2.rds.amazonaws.com',
                 dbname='mydasDev',
                 port = 5432,
                 user = 'MydasApplication',
                 password = 'gmit2017!')

############### this is for all other species from stecf ############################
stecf           = dbGetQuery(con,"SELECT * FROM data_otherstecflandings")
############### this is for stecf effort ############################
effort          = dbGetQuery(con,"SELECT * FROM data_stecfeffort")
############### this is for faocodes and price data ############################
price           = dbGetQuery(con,"SELECT * FROM data_faocodes")
############### this is for speciescodes and can link to fao codes and price data above ############################
species         = dbGetQuery(con,"SELECT * FROM data_speciescodes")
############### this is for surveybio contains halduration and no/length data ############################
survey          = dbGetQuery(con,"SELECT * FROM data_surveybio")

survey$hours    = survey$hauldur_min/60

survtots        = ddply(survey, .(year, survey_acronym, speciesgp), summarise, number=sum(number), effort=sum(hours))
survtots$cpue   = survtots$number/survtots$effort 
ggplot(survtots, aes(as.factor(year), cpue)) + geom_boxplot() + facet_wrap(~speciesgp, scale="free_y")+expand_limits(y=0)+theme_bw() + 
  theme( text = element_text(size=16), strip.text.x = element_text(size = 16),strip.text.y = element_text(size = 16),
  panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 90, hjust = 1))+ylab("year")
```



```{r, eval=FALSE}
#Ices division isnt broken down by division in North sea
land2016$division = ifelse(land2016$area %in% "4", "4A", land2016$division)
#convert in order to join and sum with landings
area$division     = ifelse(area$division %in% c("12A","12B","12C"), "12",
                   ifelse(area$division %in% c("14A","14B"), "14", area$division))
#areas not in euro zone so remove
area              = subset(area, !(area_27 %in% c("8.d.1","7.k.1","7.c.1","6.b.1","7.j.1")))
totarea           = ddply(area, .(division), summarise, totareakm=sum(area_km2))

allareas          = inner_join(land2016, totarea)
allland           = ddply(allareas, .(country, gear, mesh, stock, speciesgp, length), summarise, totland=sum(landings))
alllandarea       = ddply(allareas, .(country, gear, mesh, stock, speciesgp, length, ices_rectangle), summarise, uniarea=unique(area_km2))
allareatot        = ddply(alllandarea, .(country, gear, mesh, stock, speciesgp, length), summarise, totfleetarea=sum(uniarea))
combi             = inner_join(allland, allareatot)
divarea           = ddply(allareas, .(stock, division), summarise, area=unique(totareakm))
allstockarea      = ddply(divarea, .(stock), summarise, stockarea=sum(area))
overlap           = inner_join(combi, allstockarea)
overlap$olap_percent   = (overlap$totfleetarea/overlap$stockarea)*100
overlap$price     =  ifelse(overlap$speciesgp %in% c("BLL"), 5.62,
                    ifelse(overlap$speciesgp %in% c("TUR"), 8.54,
                    ifelse(overlap$speciesgp %in% c("LIN"), 1.22,
                    ifelse(overlap$speciesgp %in% c("JOD"), 4.38,
                    ifelse(overlap$speciesgp %in% c("SKA"), 1.22,
                    ifelse(overlap$speciesgp %in% c("SPR"), 0.20,
                    ifelse(overlap$speciesgp %in% c("POL"), 1.76,
                    ifelse(overlap$speciesgp %in% c("POK"), 1.10,
                    ifelse(overlap$speciesgp %in% c("GUG"), 1.45,
                    0)))))))))
#management categories - NEED to check, 6 = completely datapoor, 3 has LPUE time series etc for TAC
overlap$category  =  ifelse(overlap$speciesgp %in% c("BLL"), 3,
                     ifelse(overlap$speciesgp %in% c("POL"), 4,
                     ifelse(overlap$speciesgp %in% c("GUG"), 6,
                     ifelse(overlap$speciesgp %in% c("SPR"), 3, NA))))
#horizontal overlap categories 4 highest 1 lowest
overlap$score_olap = ifelse(overlap$olap_percent >40, 4,
                     ifelse(overlap$olap_percent >20 & overlap$olap_percent <40, 3,
                     ifelse(overlap$olap_percent >10 & overlap$olap_percent <20, 2,
                     ifelse(overlap$olap_percent <10, 1,  0))))
#price scoring ategories 4 highest 1 lowest
overlap$score_pr   = ifelse(overlap$price >4, 4,
                     ifelse(overlap$price >2 & overlap$price <4, 3, 
                     ifelse(overlap$price >1 & overlap$price <2, 2,
                     ifelse(overlap$price <1, 1,  0))))
#create metier
overlap            =  overlap %>% mutate(metier = paste(gear, mesh,  sep='_'))
```


```{r save}
#save(overlap,file=file.path(dirDat,"overlap.RData"),compress="xz")
```

