---
title: "Conducting Management Strategy Evaluation Using Random Search to Evaluate Pareto-Optimal Solutions"
subtitle: "Turbot Case Study"
author: "L Kell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: word_document
github_document: 
   mathjax: TRUE 
---

# Results

`r iFig=0; iTab=0 `

# Figures
```{r, knitr, eval=TRUE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)

opts_chunk$set(comment   =NA, 
               warning   =FALSE, 
               message   =FALSE, 
               error     =FALSE, 
               echo      =FALSE,
               fig.width =8, 
               fig.height=8,
               cache     =TRUE, 
               fig.path  ="../tex/figs-",
               cache.path="cache/figs/")

iFig=0
iTab=0
```
```{r, dir}  
dirOM ="/home/laurence/Desktop/sea++/mydas/project/data/OM"
dirRes="/home/laurence/Desktop/sea++/mydas/project/papers/pareto/data"
```

```{r, pkgs}
library(ggplot2)
library(plyr)
library(dplyr)
library(reshape)

library(mydas)
```
```{r}
ggplot(pm)+geom_point(aes(k1,k2,col=(plim>=0.95)))
```

**Figure `r iFig=iFig+1; iFig`.** Control parameters where P($B>B_{lim}$)>0.95


```{r, scen}
rewards=c('yield','yieldAav','kobe','safety','blim','plim')

load(file.path(dirRes,"base-turbot-pm.RData"))
load(file.path(dirRes,"base-turbot-pareto.RData"))

dat=data.frame(par=pareto$par,value=pareto$value)
names(dat)=c("k1","k2",rewards[1:4])

pts=rbind(cbind("What"="good",subset(pm,plim>=0.95)[,rewards[1:4]]),
          cbind("What"="bad", subset(pm,plim< 0.95)[,rewards[1:4]]),
          cbind("What"="fits", dat[,rewards[1:4]]))

p=ggpairs(pts,
        columns=rewards[c(1:2,4)],
        mapping = ggplot2::aes(color=What),
        #lower=list(continuous='points'), 
        lower = list(continuous = wrap("points", size = 0.1), 
                     combo = wrap("dot", alpha = 0.4)),
        #axisLabels='none',  
        diag=list(continuous="blank"),
        upper=list(continuous = wrap("points", size = 0.1), 
                     combo = wrap("dot", alpha = 0.4)))

for(i in 1:p$nrow) 
  for(j in 1:p$ncol)
    p[i,j] <- p[i,j] + 
        scale_fill_manual(values=c("green","red","black")) +
        scale_color_manual(values=c("green","red","black"))  
p  
```
**Figure `r iFig=iFig+1; iFig`.** Pairwise pareto frontiers for the Base Case.


```{r}

```

**Figure `r iFig=iFig+1; iFig`.** Pareto frontiers by scenario

```{r}

```

**Figure `r iFig=iFig+1; iFig`.** Calibration curves parameters for Base Case.

```{r}

```

**Figure `r iFig=iFig+1; iFig`.** MSE Summary.

## Tables

**Table `r iTab=iTab+1; iTab`.** Control Parameters

```{r}
```


