---
title: "Cross test using Operating Model based on Life History"
author: "L Kell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
vignette: >
  %\VignetteIndexEntry{FLife}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
github_document:
    mathjax: TRUE
tags: FLife
license: Creative Commons Attribution-ShareAlike 4.0 International Public License
---

# Fischer

Catch length frequencies were calculated based on the age distribution in the catch. Weights at age were converted firs into discrete length classes with the allometric length-weight relationship parameters, then numbers at length were spread with a normal distribution around the discrete length classes. The final length distribution was derived by aggregating numbers at age in 1cm steps. Full specifications, including equations are given in the online supplementary material.

# Geromont

The mean length of the catch, allowing for observation error, is given by:

$\hat{L}_y=\sum\limits_{a=amin}^m\hat{P}_{y,a}L_a$

where the length ($L$) of a fish at age ($a$) is assumed to be related to a von Bertalanfy growth equation

$w_a=[l_\infty(1-exp(-k(a-t_0)))]$

and 
$\hat{P}_{y,a}=P_{y,a}e^{\varphi_{y,a}-\sigma_l^2/(2P_{y,a})}$

is the model-generated proportion of fish caught of age $a$ in year $y$
which is renormalized such that $\sum\limits_{a=amin}^m\hat{P}_{y,a}=1$


In the above formulation $P_{y,a} denotes the proportion of fish of age
$a$ caught in year $y$ of the simulation, given by:

$\hat{P}_{y,a}=\frac{C_{y,a}}{\sum\limits_{a^'=min~a}^m C_{y,a^'}}$

where $C_{y,a}$ is the total number of fish caught of age $a$ in year $y$ given and $\varphi_{y,a}=N(0,\sigma^2_l/P_{y,a})$  reflects the variability for which the variance is assumed to be greater for those ages where sample sizes are smaller, where $\sigma_l$ is the coefficient of variation (CV) associated
with the mean length data. A value of $\sigma_l=0.25$ is assumed which is consistent with fisheries such as that for South African hake. This ???Punt-Kennedy??? distribution form assumption for composition data is advocated by Maunder (2011) in his comparative review of a number of such approaches.


```{r}
load("/home/laurence/Desktop/sea++/mydas/project/tasks/task4/data/turbot.RData")
  

```

