---
title: "Cross test using Operating Model based on Life History"
author: "L Kell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
vignette: >
  %\VignetteIndexEntry{FLife}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
github_document:
    mathjax: TRUE
tags: FLife
license: Creative Commons Attribution-ShareAlike 4.0 International Public License
---

```{r knitr_init, echo=FALSE, results="hide"}
library(knitr)
## Global options
opts_chunk$set(cache     =TRUE,
               cache.path="../cache/crosstest/",
               echo      =FALSE,
               eval      =TRUE,
               prompt    =FALSE,
               comment   =NA,
               message   =FALSE,
               warning   =FALSE,
               tidy      =TRUE,
               fig.height=6,
               fig.width =8,
               fig.path  ="../tex/FLife-OM-")

options(digits=3)

iFig=0
```
```{r pkgs}
library(plyr)
library(popbio)

library(FLCore)
library(ggplotFL)
library(FLife)
```
```{r, dir}
dirMy =dirname(dirname(FLife:::getScriptPath()))
dirOM ="/home/laurence/Desktop/sea++/mydas/project/data/OM"
dirRes=file.path(dirMy,"data")
```
```{r, dat}
load(file.path(dirDat,"brill.RData"))
```

## OEM
```{r, cpue, echo=TRUE, eval=TRUE}
setGeneric("cpue", function(object, ...) standardGeneric("cpue"))

#' @rdname cpue
#' @aliases cpue,FLStock-method
setMethod('cpue',   signature(object='FLStock'),
  function(object, sel=catch.sel(object), effort = c("f","h"), mass = TRUE) {

    if (effort[1] == "h")
      E <- catch(object) %/% stock(object)
    else  
      E <- fbar(object)
    
    cpue <- (catch.n(object) %*% sel) %/% E

  if (mass)
    cpue <- cpue * catch.wt(object)

  return(cpue)
  }
)
```

```{r, survey, echo=TRUE, eval=TRUE}
# survey
setGeneric("survey", function(object, ...) standardGeneric("survey"))

setMethod("survey",   signature(object="FLStock"),
  function(object, sel=stock.n(object) %=% 1, wt=stock.wt(object), timing=0.5, mass=FALSE) {
  
    timing=pmax(pmin(timing, 1.0), 0.0)

    stock.n=stock.n(object)*exp(-(harvest(object)*timing+m(object)*timing))
 
    res=stock.n%*%sel
  
    if (mass)
       res=res%*%wt

  return(res)})
```

```{r, size, echo=TRUE, eval=TRUE}
#### Indicators ################################################################
setGeneric("mnSwt", function(object,...)
   standardGeneric("mnSwt"))
setGeneric("mnCwt", function(object,...)
   standardGeneric("mnCwt"))
setGeneric("mnLwt", function(object,...)
   standardGeneric("mnLwt"))
setGeneric("mnLen", function(object,...)
   standardGeneric("mnLen"))
setGeneric("wt2z", function(object,...)
   standardGeneric("wt2z"))
setGeneric("ln2z", function(object,Linf,...)
    standardGeneric("ln2z"))

setMethod('mnSwt', signature(object='FLStock'), function(object) apply(stock.wt(   object)*stock.n(   object),2:6,sum)/apply(stock.n(   object),2:6,sum)) 
setMethod('mnCwt', signature(object='FLStock'), function(object) apply(catch.wt(   object)*catch.n(   object),2:6,sum)/apply(catch.n(   object),2:6,sum)) 
setMethod('mnLwt', signature(object='FLStock'), function(object) apply(landings.wt(object)*landings.n(object),2:6,sum)/apply(landings.n(object),2:6,sum)) 
  
setMethod('mnLen', signature(object='FLStock'), 
    function(object,a=0.001,b=3,wt="stock.wt") 
    mnLenFunc(object,a,b,wt))
setMethod('wt2z', signature(object='FLStock'), 
    function(object,a=0.001,b=3,wt="stock.wt") 
          wt2zFunc(object,a,b,wt))
setMethod('ln2z', signature(object='numeric',Linf='numeric'),
    function(object,Linf,Lc,k) 
	  ln2zFunc(object,Linf,Lc,k))
setMethod('ln2z', signature(object='numeric',Linf="FLPar"),
    function(object,Linf) 
	  ln2zFunc(object,Linf["Linf"],Linf["Lc"],Linf["k"]))

mnLenFunc<-function(object,a=0.001,b=3,wt="stock.wt"){
    wt.=slot(object,wt)
    n. =slot(object,gsub(".wt",".n",wt))

    apply((wt./a)^(1/b)*n.,c(2,6),sum)/apply(n.,c(2,6),sum)}

wt2zFunc<-function(object,Linf,Lc,k,a=0.001,b=3,wt="stock.wt"){
    mnSz<-mnSzStock(object,a,b,wt); 
    k*(Linf-mnSz)/(mnSz-Lc)}

ln2zFunc<-function(object,Linf,Lc,k){
    k*(Linf-object)/(object-Lc)}
################################################################################
```

```{r, hyperstability, eval=TRUE}
hyperstability<-function(object,omega=1,ref=apply(object,c(1,3:6),mean)) 
  ref%*%((object%/%ref)^omega)
```

```{r, trend, eval=TRUE}
trend<-function(object,bias=0.02) 
  FLQuant(cumprod(1+rep(bias,dim(object)[2])),dimnames=dimnames(object))
```

```{r, om}
theme_set(theme_bw())
plot(om)
```

**Figure `r iFig=iFig+1; iFig`,** Operating Model Time series.

```{r, oem-srvy}
set.seed(1234)
om1=iter(om,1)
u     =FLQuants("Unbiased"      =rlnorm(100,log(apply(survey(om1),2:6,sum)),.3),
                "Hyperstability"=rlnorm(100,log(apply(survey(om1),2:6,sum)%*%
                                                  hyperstability(stock(om1),0.5)),.3),
                "Hyperdepletion"=rlnorm(100,log(apply(survey(om1),2:6,sum)%*%
                                                  hyperstability(stock(om1),1.5)),0.3),
                "Trend"         =rlnorm(100,log(apply(survey(om1),2:6,sum)%*%bias(stock(om1),0.02)),.3),
                "AR"            =apply(survey(om1),2:6,sum)%*%
                                   exp(rnoise(100,apply(survey(om1),2:6,sum)*0,.3,b=.7)),
                "Juvenile"      =rlnorm(100,log(apply(survey(om1,sel=mat(om1)),2:6,sum)),.3),
                "Mature"        =rlnorm(100,log(apply(survey(om1,sel=1-mat(om1)),2:6,sum)),.3),
                "Numbers"       =rlnorm(100,log(apply(survey(om1,mass=FALSE),2:6,sum)),.3))

u=FLQuants(llply(u,function(x) x/mean(x)))
u=ldply(u,as.data.frame)

u.=ddply(u,.(year,.id), with, quantile(data))
ggplot()+
  geom_line(aes(year,data,col=factor(iter)),
            data=subset(u,iter%in%c(23,11)))+
  geom_ribbon(aes(year,ymin=`25%`,ymax=`75%`),data=u.,col="grey",alpha=.5)+
  facet_wrap(~.id,ncol=2)+
  theme_bw()+theme(legend.position="none")
```

**Figure `r iFig=iFig+1; iFig`,** Commercial indices of abundance.


```{r, oem-com}
set.seed(1234)
om1=iter(om,1)
u     =FLQuants("Unbiased"      =rlnorm(100,log(apply(cpue(om1),2:6,sum)),.3),
                "Hyperstability"=rlnorm(100,log(apply(cpue(om1),2:6,sum)%*%
                                                  hyperstability(stock(om1),0.5)),.3),
                "Hyperdepletion"=rlnorm(100,log(apply(cpue(om1),2:6,sum)%*%
                                                  hyperstability(stock(om1),1.5)),0.3),
                "Trend"         =rlnorm(100,log(apply(cpue(om1),2:6,sum)%*%bias(stock(om1),0.02)),.3),
                "AR"            =apply(cpue(om1),2:6,sum)%*%
                                   exp(rnoise(100,apply(cpue(om1),2:6,sum)*0,.3,b=.7)),
                "Juvenile"      =rlnorm(100,log(apply(cpue(om1,sel=mat(om1)),2:6,sum)),.3),
                "Mature"        =rlnorm(100,log(apply(cpue(om1,sel=1-mat(om1)),2:6,sum)),.3),
                "Numbers"       =rlnorm(100,log(apply(cpue(om1,mass=FALSE),2:6,sum)),.3))

u=FLQuants(llply(u,function(x) x/mean(x)))
u=ldply(u,as.data.frame)

u.=ddply(u,.(year,.id), with, quantile(data))
ggplot()+
  geom_line(aes(year,data,col=factor(iter)),
            data=subset(u,iter%in%c(23,11)))+
  geom_ribbon(aes(year,ymin=`25%`,ymax=`75%`),data=u.,col="grey",alpha=.5)+
  facet_wrap(~.id,ncol=2)+
  theme_bw()+theme(legend.position="none")
```

**Figure `r iFig=iFig+1; iFig`,** Survey indices of abundance.


```{r, oem-f}
theme_set(theme_bw())

plot(FLQuants(om,"F"=fbar,"Mean Size"=mnLen))
```

**Figure `r iFig=iFig+1; iFig`,** Index of F.


```{r, oem-size}
theme_set(theme_bw())

plot(mnLen(om))
```

**Figure `r iFig=iFig+1; iFig`,** Index of mean length.

## OEM
```{r, oem}
# Length frequency distribution
library(FLCore)
library(ggplotFL)
library(FLife)


load(file.path(dirOM,"turbot.RData"))

om=iter(om,1)
lh=iter(lh,1)

### Create lengths-at-age 
n=catch.n(om)
ln=vonB(ages(catch.n(om)),lh)
sd =ln*0.2
bin=0:ceiling(max(ln)*1.10)+0.5

  sim=function(ln,sd,n,bin) {data.frame(length=bin,data=dnorm(bin,ln,sd)*n)}

  lfq=ddply(model.frame(FLQuants(ln=ln,sd=sd,n=n)),.(age,year,unit,season,area,iter), 
             with, sim(ln,sd,n,bin), bin=bin)
  
  ### sum up by length 
  lfq=ddply(lfq,.(length,year,unit,season,area,iter), 
           with, data.frame(freq=sum(data)))
```


```{r, lfq}
ggplot(subset(lfq,year%in%seq(1,100,10)))+
  geom_histogram(aes(length,weight=freq),binwidth=1)+
  facet_grid(year~.,scale="free")+
  xlab("Length (cm)")+ylab("Frequency")+
   theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```


**Figure `r iFig=iFig+1; iFig`,** Length frequencies.


```{r}
Mean length data
The annual mean length of the catch, when allowing for observation error, is given by:
m
L ˆ y
P ˆ y , a L a
(S.16)
a a min
where
L a is the length of fish of age a as per the von Bertalanffy growth curve given by equation
(S.15), and
5P ˆ y , a
P y , a e
y , a
2
l /(2 P y , a )
is the mo


P ˆ y , a
P y , a e
y , a
2
l /(2 P y , a )
is the model-generated proportion of fish caught of age a in year y
m
P ˆ y , a
which is renormalized such that
1 .
a a min
In the above formulation P y , a denotes the proportion of fish of age a caught in year y of the
simulation, given by:
P y , a
C y , a
m
C y , a '
a ' a min
where C y , a is the total number of fish caught of age a in year y , given by equations (S.4), and
y , a
N (0,
2
l
/ P y , a ) reflects the variability for which the variance is assumed to be greater for
those ages where sample sizes are smaller, where
with the mean length data. A value of
l
l
is the coefficient of variation (CV) associated
0.25 is assumed which is consistent with fisheries such as
that for South African hake. This “Punt-Kennedy” distribution form assumption for composition data
is advocated by Maunder (2011) in his comparative review of a number of such approaches.

```


```{r}
This MP is similar to the Tier 4 control rule for Australian fisheries, which is based on a target CPUE
level as tested in Wayte (2009); here, however, the mean length of the catch is used in the absence of
a CPUE index. A target mean length, L t arg et , is chosen with the intention to achieve some associated
target level of abundance:
TAC y
*
TAC w (1 w )
1
L recent
L 0
y
t arg et
L
0
L
recent
if L y
L 0 (S.23)
L 0 (S.24)
and
TAC y
wTAC
1
L recent
y
*
2
0
L
recent
if L y
where
w 0.5 is the TAC smoothing parameter,
recent
TAC * is a preselected target catch (when L
L t arg et ),
1 n 1
L y ' is the historic average mean length,
10 y ' n 10
ave
L
L recent
y
1
5 y '
L t arg et
(1
y
L y ' is the average mean length over the most recent 5 years,
y 4
) L ave is the target length,
is the proportional difference between the target length and the average historic length
(values for of 0.05, 0.1 and 0.15 are considered),
L 0
0.9 L ave is the limit mean length below which future catches are reduced quadratically
rather than linearly with L and are set to zero if w 0 , and
n is the current year.
For this target-based rule, additional TAC smoothing may be required to constrain the next year’s
TAC, TAC y 1 , to increase or decrease by at most 15% from that of the previous year, i.e. let:
TAC y
1
( TAC y
1
TAC y ) / TAC y
```

