---
title: "MyDas"
subtitle: "Species Catchability"
author: "Laurie Kell & Alex Tidd"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r, knitr, echo=FALSE, results="hide"}
library(knitr)

## Global options
opts_chunk$set(echo      =FALSE,
               eval      =TRUE,
               prompt    =FALSE,
               comment   =NA,
               message   =FALSE,
               warning   =FALSE,
               tidy      =FALSE,
               fig.height=6,
               fig.width =8,
               fig.path  ="../tex/q-",
               cache     =TRUE,
               cache.path="../cache/q/")

iFig=0
iTab=0
```
```{r, pkgs}
library(ggplot2)
library(plyr)
library(dplyr)
library(reshape)

library(DBI)
library(RPostgreSQL)
```
```{r, dir, echo=FALSE}
dirMy=dirname(dirname(FLife:::getScriptPath()))
dirInp=file.path(dirMy,"inputs")
dirDat=file.path(dirMy,"data")
```
```{r, theme}
theme_set(theme_bw())
options(digits=3)
```
```{r, db}
options(scipen=999)
drv  = dbDriver("PostgreSQL")

con=dbConnect(drv, host = 'postgresql-seascope.csffkpr9jjjn.eu-west-2.rds.amazonaws.com',
                 dbname = 'mydasDev',
                 port = 5432,
                 user = 'MydasApplication',
                 password = 'gmit2017!')

survdat =dbGetQuery(con, paste0("select * from data_surveybio"))
rects   =dbGetQuery(con, paste0("select * from data_icesrects"))
#number of hauls in square
surv_eff = dbGetQuery(con, paste0("SELECT * from data_surveystns"))

surdense=survdat %>% group_by(speciesgp, year, ices_rectangle, ices_division) %>% 
                        summarise(cabund= sum(densbiom_kg_sqkm/1000)) #in tonnes per km2
```


```{r, calcs}
#Calculate total area/total number of stations the survey covered by division and merge 
#with catch tonnes perkm2
nstations = surv_eff %>% group_by(year, ices_rectangle,ices_division) %>%
            summarise(totn=length(unique(haulid))) %>% inner_join(rects)%>%
            group_by(year, ices_division)%>%summarise(totarea=sum(area_km2), totstn=sum(totn)) %>% inner_join(surdense)

#Biomass = totalsurveyarea*1/total number of stations within the survey area * sum of catch
nstations$relabund = ((nstations$totarea))*(1/nstations$totstn)*nstations$cabund
nstations2 = nstations %>%group_by(year, speciesgp) %>% summarise(totabund= sum(relabund), variance= var(relabund))

stecfdat  = dbGetQuery(con, paste0("select * from data_stecf_aer_cpuedays"))
#assuming cpue=qN

catchq    = stecfdat %>% inner_join(nstations2)  %>% mutate(q=(totctch/totdays)/totabund) %>%
            group_by(year, gear_type, speciesgp) %>% summarise(mn_q=mean(q),  y10=quantile(q, 0.10), y90=quantile(q,0.90), y25= quantile(q, 0.25), y75=quantile(q, 0.75)) 

summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {

  
  # New version of length which can handle NA's: if na.rm==T, don't count them
  length2 <- function (x, na.rm=FALSE) {
    if (na.rm) sum(!is.na(x))
    else       length(x)
  }
  
  # This does the summary. For each group's data frame, return a vector with
  # N, mean, and sd
  datac <- ddply(data, groupvars, .drop=.drop,
                 .fun = function(xx, col) {
                   c(N    = length2(xx[[col]], na.rm=na.rm),
                     mean = mean   (xx[[col]], na.rm=na.rm),
                     sd   = sd     (xx[[col]], na.rm=na.rm)
                   )
                 },
                 measurevar
  )
  
  # Rename the "mean" column    
  datac <- rename(datac, c("mean" = measurevar))
  
  datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean
  
  # Confidence interval multiplier for standard error
  # Calculate t-statistic for confidence interval: 
  # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
  ciMult <- qt(conf.interval/2 + .5, datac$N-1)
  datac$ci <- datac$se * ciMult
  
  return(datac)
}
###################Take this dataframe for q analysis #######################################
catchq2= stecfdat %>% inner_join(nstations2)  %>% mutate(q=(totctch/totdays)/totabund) 

q <- summarySE(catchq2, measurevar="q", groupvars=c("year","gear_type","speciesgp"))
```

```{r, q}
ggplot(q)+
  geom_histogram(aes(q,fill=gear_type))+
  scale_x_log10()+
  facet_wrap(~speciesgp)+
  theme_bw()+
  theme(legend.position="none")

save(q,file=file.path(dirDat,"q.RData"))
```

**Figure `r iFig=iFig+1; iFig`** q.

```{r}
tmp=ddply(subset(catchq2,speciesgp!="SPR"),.(speciesgp,gear_type),with,sum(totctch))
tmp=ddply(tmp,.(speciesgp),mutate,pcnt=V1/sum(V1))
tmp=tmp[rev(do.call("order",tmp[,c("speciesgp","pcnt")])),]
mnGr=unique(subset(tmp,pcnt>.1)$gear_type)

catchq3=mutate(subset(catchq2,speciesgp!="SPR"),
               gear=ifelse(gear_type%in%mnGr,gear_type,"OTH"))
q2=summarySE(catchq3, measurevar="q", groupvars=c("year","gear","speciesgp"))
```

```{r}
ggplot(q2,aes(q,fill=gear))+
  geom_histogram(aes(y = ..density..))+
  #geom_density(alpha=.5)+
  scale_x_log10()+
  facet_wrap(~speciesgp)+
  theme_bw()+
  theme(legend.position="bottom")
```

**Figure `r iFig=iFig+1; iFig`** q main gears.


```{r}
ggplot(q2,aes(q,fill=gear))+
  #geom_histogram(aes(y = ..density..))+
  geom_density(alpha=.5)+
  scale_x_log10()+
  facet_wrap(~speciesgp)+
  theme_bw()+
  theme(legend.position="bottom")
```

**Figure `r iFig=iFig+1; iFig`** q main gears.
