---
title: "MyDas"
subtitle: "Species Catchability"
author: "Laurie Kell & Alex Tidd"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r, knitr, echo=FALSE, results="hide"}
library(knitr)

## Global options
opts_chunk$set(echo      =FALSE,
               eval      =TRUE,
               prompt    =FALSE,
               comment   =NA,
               message   =FALSE,
               warning   =FALSE,
               tidy      =FALSE,
               fig.height=6,
               fig.width =8,
               fig.path  ="../tex/q-",
               cache     =TRUE,
               cache.path="../cache/q/")

iFig=0
iTab=0
```
```{r, pkgs}
library(ggplot2)
library(plyr)
library(dplyr)
library(reshape)

library(DBI)
library(RPostgreSQL)
```
```{r, dir, echo=FALSE}
dirMy=dirname(dirname(FLife:::getScriptPath()))
dirInp=file.path(dirMy,"inputs")
dirDat=file.path(dirMy,"data")
```
```{r, theme}
theme_set(theme_bw())
options(digits=3)
```
```{r, data}
load(file.path(dirDat,"q.RData"))
load(file.path(dirDat,"r.RData"))
```

```{r}
r=melt(r)
names(r)=c("spp","iter","r")
q=q[,c(3,5)]
names(q)=c("spp","q")
q=ddply(q,.(spp),with,data.frame(iter=seq(500),q=sample(q,500,replace=TRUE)))

res=merge(r,q)
res=ddply(res,.(spp),with,data.frame(r=diags:::stdz(r),q=diags:::stdz(q)))

ggplot(res, aes(q,r, group=spp, col=spp, fill=spp)) +
  geom_point() +
  stat_ellipse()+
  scale_x_log10()+
  scale_y_log10(limits=c(.1,25.0))+
  theme(legend.position="bottom")
```

**Figure `r iFig=iFig+1; iFig`** q.

